### ISSUE TITLE
Is there demand/interest for a package on ical?

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci-archive/onboarding-guide#1]
First-up, not sure if this is the right place for a pre-onboarding but https://github.com/ropensci/onboarding/issues/ didn't seem appropriate and I could find anywhere better. Any suggestions of a better place for this welcome!

So, is there unmet demand for an **ical** package? Context: https://twitter.com/robinlovelace/status/1026750997199245312 starter repo: https://github.com/ATFutures/ical

Discussed with @layik today.

**Comment by sckott** [comment]
right place would be the onboarding repo, just open an issue there. 

in this case, i don't think ical would be a good fit unless there's some research use cases that I don't know about?  

any thoughts @maelle ?

**Comment by Robinlovelace** [comment]
OK thanks for the input. We were thinking of using integrating with the **gtfs** package and perhaps other ones. Happy to develop it and see if, after initial dev work, any use cases emerge.
